parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        # See https://marenkay.com/2018/06/12/symfony-doctrine-mariadb/
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        types:
            JournalEntryEnumType: Kontrolgruppen\CoreBundle\DBAL\Types\JournalEntryEnumType
            ProcessLogEntryLevelEnumType: Kontrolgruppen\CoreBundle\DBAL\Types\ProcessLogEntryLevelEnumType
            EconomyEntryEnumType: Kontrolgruppen\CoreBundle\DBAL\Types\EconomyEntryEnumType
            RevenueTypeEnumType: Kontrolgruppen\CoreBundle\DBAL\Types\RevenueTypeEnumType
            RevenueFutureTypeEnumType: Kontrolgruppen\CoreBundle\DBAL\Types\RevenueFutureTypeEnumType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            gedmo_loggable:
                type: annotation
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/src/Loggable/Entity/"
                is_bundle: false
        dql:
            datetime_functions:
                YEAR: DoctrineExtensions\Query\Mysql\Year
                MONTH: DoctrineExtensions\Query\Mysql\Month
                WEEK: DoctrineExtensions\Query\Mysql\Week
