framework:
    router:
        strict_requirements: ~
        utf8: true
        default_uri: '%env(DEFAULT_URI)%'

when@dev:
    framework:
        router:
            strict_requirements: true

when@test:
    framework:
        router:
            strict_requirements: true
