security:
    role_hierarchy:
        ROLE_PROCESS_VIEW:  [ROLE_USER, ROLE_SEARCH]
        ROLE_SAGSBEHANDLER: [ROLE_USER, ROLE_SEARCH]
        ROLE_BI:            ROLE_USER
        ROLE_ADMIN:         [ROLE_USER, ROLE_SAGSBEHANDLER, ROLE_PROCESS_VIEW]
        ROLE_SUPER_ADMIN:   [ROLE_ADMIN, ROLE_BI]

    providers:
        saml:
            id: Kontrolgruppen\CoreBundle\Security\SAMLUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true

            custom_authenticators:
                - Kontrolgruppen\CoreBundle\Security\SAMLAuthenticator
                - Kontrolgruppen\CoreBundle\Security\CliLoginTokenAuthenticator
            form_login:
                login_path:          /saml/login
                default_target_path: /saml/login
                always_use_default_target_path: true

    access_control:
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/saml, role: PUBLIC_ACCESS }
        - { path: ^/bi/, role: ROLE_BI }
        - { path: ^/, role: ROLE_USER }

    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
