version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    networks:
      - app
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: db
      PMA_PASSWORD: db

  phpfpm:
    build: docker/php-fpm
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 9000
    networks:
      - app
    depends_on:
      - mariadb
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/app:delegated
      - ./docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini
    tmpfs:
      - /app/var:size=1G
      - /tmp:size=1G

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - 80:8080
    volumes:
      - ${PWD}/docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"

  mailhog:
    image: itkdev/mailhog
    networks:
      - app
      - frontend
    ports:
      - "1025"
      - "8025"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}Mailhog.rule=Host(`mailhog-${COMPOSE_DOMAIN}`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME}Mailhog.loadbalancer.server.port=8025"

  borgerdata:
    image: docker.pkg.github.com/itk-dev/borgerdata/app:latest
    networks:
      - app
    ports:
      - "8081"
    depends_on:
      - sqlserver
    environment:
      - NODE_ENV=development
      - APP_PORT=8081
      - SQL_SERVER=sqlserver
      - SQL_PORT=1433
      - SQL_USER=sa
      - SQL_PASSWORD=VeryStrongPassword1
      - SQL_DATABASE=dataintegration
      - SQL_SCHEMA=dbo
      - SQL_TABLE=Udvalgte_borgerdata
      # - SQL_DOMAIN=

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - app
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VeryStrongPassword1
    ports:
      - "1433"

  node:
    # Node LTS (cf. https://nodejs.org/en/about/releases/)
    image: node:16
    volumes:
      - ./:/app:delegated
    working_dir: /app
