version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    networks:
      - app
    ports:
      - '8080'
    environment:
      PMA_HOST: mariadb
      PMA_USER: db
      PMA_PASSWORD: db

  phpfpm:
    build: docker/php-fpm
    extra_hosts:
      - host.docker.internal:host-gateway
    expose:
      - 9000
    networks:
      - app
    depends_on:
      - mariadb
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - DOCKER_HOST_DOMAIN=${COMPOSE_DOMAIN}
      - COMPOSER_VERSION=2
      - PHP_IDE_CONFIG=serverName=localhost
    volumes:
      - .:/app:delegated
      - ./.docker/php-fpm/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini
    tmpfs:
      - /app/var:size=1G
      - /tmp:size=1G

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - '8080'
    volumes:
      - ./.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated

  mailhog:
    image: itkdev/mailhog
    networks:
      - app
      - frontend
    ports:
      - "1025"
      - "8025"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    networks:
      - app
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=VeryStrongPassword1
    ports:
      - '1433'

  node:
    image: node:18
    volumes:
      - ./:/app:delegated
    working_dir: /app
