version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  mariadb:
    image: itkdev/mariadb:latest
    networks:
      - app
    ports:
      - '3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=db
      - MYSQL_PASSWORD=db
      - MYSQL_DATABASE=db
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  phpfpm:
    build: docker/php-fpm
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - app
    depends_on:
      - mariadb
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=256M
      - COMPOSER_VERSION=2
    volumes:
      - .:/app:delegated

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: always
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - 80:8080
    volumes:
      - ${PWD}/docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:rw
