version: "3"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  phpfpm:
    build: docker/php-fpm
    networks:
      - app
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=128M
      - COMPOSER_VERSION=2
    volumes:
      - .:/app:delegated

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: always
    networks:
      - app
      - frontend
    depends_on:
      - phpfpm
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:rw
      - ./certs:/etc/nginx/certs
