<?php

/*
 * This file is part of itk-dev/kontrolgruppen.
 *
 * (c) 2019–2021 ITK Development
 *
 * This source file is subject to the MIT license.
 */

namespace Kontrolgruppen\CoreBundle\BBR;

/**
 * Enum Bygge Anvendelse.
 */
final class BBRKoder
{
    public const BYG_ANVENDELSE = [
        '110' => 'Stuehus til landbrugsejendom',
        '120' => 'Fritliggende enfamiliehus',
        '121' => 'Sammenbygget enfamiliehus',
        '122' => 'Fritliggende enfamiliehus i tæt-lav bebyggelse',
        '130' => '(UDFASES) Række-, kæde-, eller dobbelthus (lodret adskillelse mellem enhederne).',
        '131' => 'Række-, kæde- og klyngehus',
        '132' => 'Dobbelthus',
        '140' => 'Etagebolig-bygning, flerfamiliehus eller to-familiehus',
        '150' => 'Kollegium',
        '160' => 'Boligbygning til døgninstitution',
        '185' => 'Anneks i tilknytning til helårsbolig.',
        '190' => 'Anden bygning til helårsbeboelse',
        '210' => '(UDFASES) Bygning til erhvervsmæssig produktion vedrørende landbrug, gartneri, råstofudvinding o. lign',
        '211' => 'Stald til svin',
        '212' => 'Stald til kvæg, får mv.',
        '213' => 'Stald til fjerkræ',
        '214' => 'Minkhal',
        '215' => 'Væksthus',
        '216' => 'Lade til foder, afgrøder mv.',
        '217' => 'Maskinhus, garage mv.',
        '218' => 'Lade til halm, hø mv.',
        '219' => 'Anden bygning til landbrug mv.',
        '220' => '(UDFASES) Bygning til erhvervsmæssig produktion vedrørende industri, håndværk m.v. (fabrik, værksted o.lign.)',
        '221' => 'Bygning til industri med integreret produktionsapparat',
        '222' => 'Bygning til industri uden integreret produktionsapparat',
        '223' => 'Værksted',
        '229' => 'Anden bygning til produktion',
        '230' => '(UDFASES) El-, gas-, vand- eller varmeværk, forbrændingsanstalt m.v.',
        '231' => 'Bygning til energiproduktion',
        '232' => 'Bygning til energidistribution',
        '233' => 'Bygning til vandforsyning',
        '234' => 'Bygning til håndtering af affald og spildevand',
        '239' => 'Anden bygning til energiproduktion og forsyning',
        '290' => '(UDFASES) Anden bygning til landbrug, industri etc.',
        '310' => '(UDFASES) Transport- og garageanlæg (fragtmandshal, lufthavnsbygning, banegårdsbygning, parkeringshus). Garage med plads til et eller to køretøjer registreres med anvendelseskode 910',
        '311' => 'Bygning til jernbane- og busdrift',
        '312' => 'Bygning til luftfart',
        '313' => 'Bygning til parkering- og transportanlæg',
        '314' => 'Bygning til parkering af flere end to køretøjer i tilknytning til boliger',
        '315' => 'Havneanlæg',
        '319' => 'Andet transportanlæg',
        '320' => '(UDFASES) Bygning til kontor, handel, lager, herunder offentlig administration',
        '321' => 'Bygning til kontor',
        '322' => 'Bygning til detailhandel',
        '323' => 'Bygning til lager',
        '324' => 'Butikscenter',
        '325' => 'Tankstation',
        '329' => 'Anden bygning til kontor, handel og lager',
        '330' => '(UDFASES) Bygning til hotel, restaurant, vaskeri, frisør og anden servicevirksomhed',
        '331' => 'Hotel, kro eller konferencecenter med overnatning',
        '332' => 'Bed & breakfast mv.',
        '333' => 'Restaurant, café og konferencecenter uden overnatning',
        '334' => 'Privat servicevirksomhed som frisør, vaskeri, netcafé mv.',
        '339' => 'Anden bygning til serviceerhverv',
        '390' => '(UDFASES) Anden bygning til transport, handel etc',
        '410' => '(UDFASES) Bygning til biograf, teater, erhvervsmæssig udstilling, bibliotek, museum, kirke o. lign.',
        '411' => 'Biograf, teater, koncertsted mv.',
        '412' => 'Museum',
        '413' => 'Bibliotek',
        '414' => 'Kirke eller anden bygning til trosudøvelse for statsanerkendte trossamfund',
        '415' => 'Forsamlingshus',
        '416' => 'Forlystelsespark',
        '419' => 'Anden bygning til kulturelle formål',
        '420' => '(UDFASES) Bygning til undervisning og forskning (skole, gymnasium, forskningslabratorium o.lign.).',
        '421' => 'Grundskole',
        '422' => 'Universitet',
        '429' => 'Anden bygning til undervisning og forskning',
        '430' => '(UDFASES) Bygning til hospital, sygehjem, fødeklinik o. lign.',
        '431' => 'Hospital og sygehus',
        '432' => 'Hospice, behandlingshjem mv.',
        '433' => 'Sundhedscenter, lægehus, fødeklinik mv.',
        '439' => 'Anden bygning til sundhedsformål',
        '440' => '(UDFASES) Bygning til daginstitution',
        '441' => 'Daginstitution',
        '442' => 'Servicefunktion på døgninstitution',
        '443' => 'Kaserne',
        '444' => 'Fængsel, arresthus mv.',
        '449' => 'Anden bygning til institutionsformål',
        '451' => 'Beskyttelsesrum',
        '490' => '(UDFASES) Bygning til anden institution, herunder kaserne, fængsel o. lign.',
        '510' => 'Sommerhus',
        '520' => '(UDFASES) Bygning til feriekoloni, vandrehjem o.lign. bortset fra sommerhus',
        '521' => 'Feriecenter, center til campingplads mv.',
        '522' => 'Bygning med ferielejligheder til erhvervsmæssig udlejning',
        '523' => 'Bygning med ferielejligheder til eget brug',
        '529' => 'Anden bygning til ferieformål',
        '530' => '(UDFASES) Bygning i forbindelse med idrætsudøvelse (klubhus, idrætshal, svømmehal o. lign.)',
        '531' => 'Klubhus i forbindelse med fritid og idræt',
        '532' => 'Svømmehal',
        '533' => 'Idrætshal',
        '534' => 'Tribune i forbindelse med stadion',
        '535' => 'Bygning til træning og opstaldning af heste',
        '539' => 'Anden bygning til idrætformål',
        '540' => 'Kolonihavehus',
        '585' => 'Anneks i tilknytning til fritids- og sommerhus',
        '590' => 'Anden bygning til fritidsformål',
        '910' => 'Garage',
        '920' => 'Carport',
        '930' => 'Udhus',
        '940' => 'Drivhus',
        '950' => 'Fritliggende overdækning',
        '960' => 'Fritliggende udestue',
        '970' => 'Tiloversbleven landbrugsbygning',
        '990' => 'Faldefærdig bygning',
        '999' => 'Ukendt bygning',
    ];
}
