services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Kontrolgruppen\CoreBundle\CPR\CprServiceInterface:
        class: 'Kontrolgruppen\CoreBundle\CPR\ServiceplatformenCprService'
        arguments:
            $dataFordelerController: '@Kontrolgruppen\CoreBundle\Controller\DatafordelerController'
            $httpClient: '@datafordelerHttpClient'  # Note the name change


    Kontrolgruppen\CoreBundle\Controller\DatafordelerController:
        arguments:
            $datafordelerHttpClient: '@datafordelerHttpClient'  # Note the name change
        tags:
            - { name: 'controller.service_arguments' }  