# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(ROUTER_REQUEST_CONTEXT_BASE_URL): ''
    locale: 'da'
    mailer_user: '%env(MAILER_FROM)%'
    router.request_context.scheme: '%env(ROUTER_REQUEST_CONTEXT_SCHEME)%'
    router.request_context.host: '%env(ROUTER_REQUEST_CONTEXT_HOST)%'
    router.request_context.base_url: '%env(ROUTER_REQUEST_CONTEXT_BASE_URL)%'
    base_url: '%router.request_context.scheme%://%router.request_context.host%%router.request_context.base_url%'
    export_directory: '%env(resolve:EXPORT_DIRECTORY)%'
    azure_tenant_id: '%env(AZURE_TENANT_ID)%'
    azure_application_id: '%env(AZURE_APPLICATION_ID)%'
    azure_client_secret: '%env(AZURE_CLIENT_SECRET)%'
    azure_key_vault_name: '%env(AZURE_KEY_VAULT_NAME)%'
    azure_key_vault_secret: '%env(AZURE_KEY_VAULT_SECRET)%'
    azure_key_vault_secret_version: '%env(AZURE_KEY_VAULT_SECRET_VERSION)%'
    serviceplatformen_service_agreement_uuid: '%env(SERVICEPLATFORMEN_SERVICE_AGREEMENT_UUID)%'
    serviceplatformen_user_system_uuid: '%env(SERVICEPLATFORMEN_USER_SYSTEM_UUID)%'
    serviceplatformen_user_uuid: '%env(SERVICEPLATFORMEN_USER_UUID)%'
    company_base_data_extended_service_contract: '%kernel.project_dir%/%env(COMPANY_BASE_DATA_EXTENDED_SERVICE_CONTRACT)%'
    company_base_data_extended_service_endpoint: '%env(COMPANY_BASE_DATA_EXTENDED_SERVICE_ENDPOINT)%'
    company_base_data_extended_service_uuid: '%env(COMPANY_BASE_DATA_EXTENDED_SERVICE_UUID)%'
    person_base_data_extended_service_contract: '%kernel.project_dir%/%env(PERSON_BASE_DATA_EXTENDED_SERVICE_CONTRACT)%'
    person_base_data_extended_service_endpoint: '%env(PERSON_BASE_DATA_EXTENDED_SERVICE_ENDPOINT)%'
    person_base_data_extended_service_uuid: '%env(PERSON_BASE_DATA_EXTENDED_SERVICE_UUID)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
