#!/usr/bin/env bash
set -o errexit -o errtrace -o noclobber -o nounset -o pipefail
IFS=$'\n\t'

dir=$(cd $(dirname "${BASH_SOURCE[0]}")/../ && pwd)
bold=$(tput bold)
normal=$(tput sgr0)

git_tag=${1:-}
if [ -z "$git_tag" ]; then
	(>&2 echo "Usage: $0 git-tag")
	exit
fi

cd $dir

git checkout $git_tag
git reset origin/$git_tag --hard
git pull

# git -C bundles/kontrolgruppen-core-bundle/ checkout develop
# git -C bundles/kontrolgruppen-core-bundle/ reset origin/develop --hard

# Build and deploy assets
yarn install
yarn build
rsync -rav public/prod stg.kontrolgruppen.itkdev.dk:/home/www/stg_kontrolgruppen_itkdev_dk/htdocs/public

ssh stg.kontrolgruppen.itkdev.dk /home/www/stg_kontrolgruppen_itkdev_dk/scripts/deploy $git_tag
