controllers:
    resource: "@KontrolgruppenCoreBundle/Controller"
    type: annotation

cli_login:
    path: /cli-login

logout:
    path: /logout

_wdt:
    path: /_wdt/{token}
    methods: GET
    defaults:
        _controller: Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController::wdtAction

_profiler:
    path: /_profiler
    methods: GET
    defaults:
        _controller: Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController::indexAction

_profiler_home:
    path: /_profiler
    methods: GET
    defaults:
        _controller: Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController::homeAction