on: pull_request
name: Review
jobs:
    test-composer-files:
        name: Validate composer
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   name: Setup PHP, with composer and extensions
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    extensions: ctype, dom, gd, iconv, json, soap, zip
                    coverage: none
                    tools: composer:v2
            -   name: Validate composer files
                run: |
                    composer validate composer.json

    runner-phpcs:
        name: runner-phpcs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: ctype, dom, gd, iconv, json, soap, zip
                  coverage: none
                  tools: composer:v2
            - name: Install Reviewdog
              run: |
                  wget -O - -q https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $PWD/ v0.9.14
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: PHPCS
              run: |
                  composer actions/phpcs | ./reviewdog -f=checkstyle -name=PHPCS -reporter=github-pr-check
              env:
                  REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    phpcsfixer:
        name: PHP-CS-FIXER
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: ctype, dom, gd, iconv, json, soap, zip
                  coverage: none
                  tools: composer:v2
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: phpcsfixerr
              run: |
                  composer actions/phpcsfixer

    twigcs:
        name: TwigCS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: ctype, dom, gd, iconv, json, soap, zip
                  coverage: none
                  tools: composer:v2
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - name: twigcs
              run: |
                  composer actions/twigcs

    js-coding-standards:
        name: JS coding standards
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.4
                  extensions: ctype, dom, gd, iconv, json, soap, zip
                  coverage: none
                  tools: composer:v2
            - name: Install Dependencies
              run: |
                  composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
            - uses: actions/setup-node@v1
              with:
                  # Node LTS (cf. https://nodejs.org/en/about/releases/)
                  node-version: '16.x'
            - name: install
              run: |
                  yarn install
            - name: JS coding standards
              run: |
                  yarn check-coding-standards

    tests:
        name: Tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@master
          - name: Setup PHP, with composer and extensions
            uses: shivammathur/setup-php@v2
            with:
                php-version: 7.4
                extensions: ctype, dom, gd, iconv, json, pdo, soap, sqlite3, zip
                coverage: none
                tools: composer:v2
          - name: Install Dependencies
            run: |
              composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          - name: Tests
            run: |
                composer actions/tests
